### ISSUE TITLE
EdmContainerElementKind

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#12]
EdmContainerElementKindinteger($int32)

0 - None; 1 - EntitySet; 2 - ActionImport; 3 - FunctionImport; 4 - Singleton;
Enum:
[ 0, 1, 2, 3, 4 ]

![image](https://user-images.githubusercontent.com/5001708/146328474-4f6b1418-4eb6-4ec7-9d3f-9bde9ff860ed.png)

**Comment by ariantron** [comment]
4c0443a
