### ISSUE TITLE
EdmExpressionKind

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#13]
EdmExpressionKindinteger($int32)

0 - None; 1 - BinaryConstant; 2 - BooleanConstant; 3 - DateTimeOffsetConstant; 4 - DecimalConstant; 5 - FloatingConstant; 6 - GuidConstant; 7 - IntegerConstant; 8 - StringConstant; 9 - DurationConstant; 10 - Null; 11 - Record; 12 - Collection; 13 - Path; 14 - If; 15 - Cast; 16 - IsType; 17 - FunctionApplication; 18 - LabeledExpressionReference; 19 - Labeled; 20 - PropertyPath; 21 - NavigationPropertyPath; 22 - DateConstant; 23 - TimeOfDayConstant; 24 - EnumMember; 25 - AnnotationPath;
Enum:
[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 ]

![image](https://user-images.githubusercontent.com/5001708/146328542-f7ef681d-bb27-4f26-97dc-12abf900f223.png)

**Comment by ariantron** [comment]
caab966
