### ISSUE TITLE
EdmSchemaElementKind

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#14]
EdmSchemaElementKindinteger($int32)

0 - None; 1 - TypeDefinition; 2 - Term; 3 - Action; 4 - EntityContainer; 5 - Function;
Enum:
[ 0, 1, 2, 3, 4, 5 ]

![image](https://user-images.githubusercontent.com/5001708/146328615-139bb6c4-486c-4d8e-ab30-cc98c6e862a2.png)

**Comment by ariantron** [comment]
f3d82cf
