### ISSUE TITLE
EdmTypeKind

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#15]
EdmTypeKindinteger($int32)

0 - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 - EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;
Enum:
[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]

![image](https://user-images.githubusercontent.com/5001708/146328688-c8704e0f-8555-4f67-8c4b-085ca0852b5b.png)

**Comment by ariantron** [comment]
a6e3343
