### ISSUE TITLE
GiftVoucherType

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#16]
GiftVoucherTypeinteger($int32)

0 - Virtual; 1 - Physical;
Enum:
[ 0, 1 ]

![image](https://user-images.githubusercontent.com/5001708/146328744-436cfaf7-2f62-4621-a2cf-1b792c9e9402.png)

**Comment by yamin8000** [comment]
[b2e0b84e429335c11ea06a423511e2fd63881a78](https://github.com/Arian-Tech/Market/commit/b2e0b84e429335c11ea06a423511e2fd63881a78)

**Comment by ariantron** [comment]
999401b
