### ISSUE TITLE
IEdmTypeReference

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#18]
<html><body>
<span class="model-box"><div class="model-box"><span class="model"><span class=""><button aria-expanded="true" class="model-box-control"><span class="pointer"><span class="model-title"><span class="model-title__text">IEdmTypeReference</span></span></span><span class="model-toggle"></span></button><span class="brace-open object">{</span><span class="inner-object">

isNullable | booleanreadOnly: true
-- | --
definition | IEdmType{typeKindEdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]} | typeKind | EdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
typeKind | EdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]

</span><span class="brace-close">}</span></span></span></div></span>
</body>
</html>

![image](https://user-images.githubusercontent.com/5001708/146330724-e173467e-1a59-4cf9-badf-27162fc3441f.png)

**Comment by ariantron** [comment]
e331e84

**Comment by ariantron** [comment]
077e8e1
