### ISSUE TITLE
IEdmTerm

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#19]
<html><body>
<span class="model-box"><div class="model-box"><span class="model"><span class=""><button aria-expanded="true" class="model-box-control"><span class="pointer"><span class="model-title"><span class="model-title__text">IEdmTerm</span></span></span><span class="model-toggle"></span></button><span class="brace-open object">{</span><span class="inner-object">

type | IEdmTypeReference{isNullablebooleanreadOnly: truedefinitionIEdmType{typeKindEdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]}} | isNullable | booleanreadOnly: true | definition | IEdmType{typeKindEdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]} | typeKind | EdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
-- | -- | -- | -- | -- | -- | -- | --
isNullable | booleanreadOnly: true
definition | IEdmType{typeKindEdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]} | typeKind | EdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
typeKind | EdmTypeKindinteger($int32)0  - None; 1 - Primitive; 2 - Entity; 3 - Complex; 4 - Collection; 5 -  EntityReference; 6 - Enum; 7 - TypeDefinition; 8 - Untyped; 9 - Path;Enum:[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
appliesTo | stringnullable: truereadOnly: true
defaultValue | stringnullable: truereadOnly: true
schemaElementKind | EdmSchemaElementKindinteger($int32)0 - None; 1 - TypeDefinition; 2 - Term; 3 - Action; 4 - EntityContainer; 5 - Function;Enum:[ 0, 1, 2, 3, 4, 5 ]
namespace | stringnullable: truereadOnly: true
name | stringnullable: truereadOnly: true

</span><span class="brace-close">}</span></span></span></div></span>
</body>
</html>

![image](https://user-images.githubusercontent.com/5001708/146330563-c4cf03e9-6e2b-44c1-ac2c-877177a63653.png)

**Comment by ariantron** [comment]
9dfc5e9
