### ISSUE TITLE
AddressDto

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#2]
<html><body>
<span class="model-box"><div class="model-box"><span class="model"><span class=""><button aria-expanded="true" class="model-box-control"><span class="pointer"><span class="model-title"><span class="model-title__text">AddressDto</span></span></span><span class="model-toggle"></span></button><span class="brace-open object">{</span><span class="inner-object">

id | stringnullable: true
-- | --
firstName | stringnullable: true
lastName | stringnullable: true
email | stringnullable: true
company | stringnullable: true
vatNumber | stringnullable: true
countryId | stringnullable: true
stateProvinceId | stringnullable: true
city | stringnullable: true
address1 | stringnullable: true
address2 | stringnullable: true
zipPostalCode | stringnullable: true
phoneNumber | stringnullable: true
faxNumber | stringnullable: true
note | stringnullable: true
addressType | integer($int32)
createdOnUtc | string($date-time)

</span><span class="brace-close">}</span></span></span></div></span>
</body>
</html>

![image](https://user-images.githubusercontent.com/5001708/146327517-5e0ee12b-8df2-436e-9e6c-4bbf5204e5d7.png)

**Comment by ariantron** [comment]
1adab4c
