### ISSUE TITLE
CollectionDto

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#7]
<html><body>
<span class="model-box"><div class="model-box"><span class="model"><span class=""><button aria-expanded="true" class="model-box-control"><span class="pointer"><span class="model-title"><span class="model-title__text">CollectionDto</span></span></span><span class="model-toggle"></span></button><span class="brace-open object">{</span><span class="inner-object">

id | stringnullable: true
-- | --
name | stringnullable: true
seName | stringnullable: true
description | stringnullable: true
bottomDescription | stringnullable: true
collectionLayoutId | stringnullable: true
metaKeywords | stringnullable: true
metaDescription | stringnullable: true
metaTitle | stringnullable: true
pictureId | stringnullable: true
pageSize | integer($int32)
allowCustomersToSelectPageSize | boolean
pageSizeOptions | stringnullable: true
showOnHomePage | boolean
featuredProductsOnHomePage | boolean
includeInMenu | boolean
icon | stringnullable: true
published | boolean
externalId | stringnullable: true
displayOrder | integer($int32)

</span><span class="brace-close">}</span></span></span></div></span>
</body>
</html>

![image](https://user-images.githubusercontent.com/5001708/146328035-acfa268b-af72-4a10-b679-24f1092de400.png)

**Comment by MansourM** [comment]
8906d21b8459fa6077f2470671bf7f56ecd61724
