### ISSUE TITLE
CustomerDto

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/grand-node-java-client#8]
<html><body>
<span class="model-box"><div class="model-box"><span class="model"><span class=""><button aria-expanded="true" class="model-box-control"><span class="pointer"><span class="model-title"><span class="model-title__text">CustomerDto</span></span></span><span class="model-toggle"></span></button><span class="brace-open object">{</span><span class="inner-object">

id | stringnullable: true
-- | --
customerGuid | string($uuid)
username | stringnullable: true
email | stringnullable: true
adminComment | stringnullable: true
isTaxExempt | boolean
freeShipping | boolean
affiliateId | stringnullable: true
vendorId | stringnullable: true
storeId | stringnullable: true
active | boolean
deleted | boolean
gender | stringnullable: true
firstName | stringnullable: true
lastName | stringnullable: true
dateOfBirth | string($date-time)nullable: true
company | stringnullable: true
streetAddress | stringnullable: true
streetAddress2 | stringnullable: true
zipPostalCode | stringnullable: true
city | stringnullable: true
countryId | stringnullable: true
stateProvinceId | stringnullable: true
phone | stringnullable: true
fax | stringnullable: true
vatNumber | stringnullable: true
vatNumberStatusId | stringnullable: true
groups | [nullable: truestring]
addresses | [nullable: trueAddressDto{idstringnullable: truefirstNamestringnullable: truelastNamestringnullable: trueemailstringnullable: truecompanystringnullable: truevatNumberstringnullable: truecountryIdstringnullable: truestateProvinceIdstringnullable: truecitystringnullable: trueaddress1stringnullable: trueaddress2stringnullable: truezipPostalCodestringnullable: truephoneNumberstringnullable: truefaxNumberstringnullable: truenotestringnullable: trueaddressTypeinteger($int32)createdOnUtcstring($date-time)}] | id | stringnullable: true | firstName | stringnullable: true | lastName | stringnullable: true | email | stringnullable: true | company | stringnullable: true | vatNumber | stringnullable: true | countryId | stringnullable: true | stateProvinceId | stringnullable: true | city | stringnullable: true | address1 | stringnullable: true | address2 | stringnullable: true | zipPostalCode | stringnullable: true | phoneNumber | stringnullable: true | faxNumber | stringnullable: true | note | stringnullable: true | addressType | integer($int32) | createdOnUtc | string($date-time)
id | stringnullable: true
firstName | stringnullable: true
lastName | stringnullable: true
email | stringnullable: true
company | stringnullable: true
vatNumber | stringnullable: true
countryId | stringnullable: true
stateProvinceId | stringnullable: true
city | stringnullable: true
address1 | stringnullable: true
address2 | stringnullable: true
zipPostalCode | stringnullable: true
phoneNumber | stringnullable: true
faxNumber | stringnullable: true
note | stringnullable: true
addressType | integer($int32)
createdOnUtc | string($date-time)

</span><span class="brace-close">}</span></span></span></div></span>
</body>
</html>

![image](https://user-images.githubusercontent.com/5001708/146328144-bf0ceaad-2fbd-4bde-bd81-390c159748a6.png)

**Comment by MansourM** [comment]
f6f76e1e00e59505d000a3327fc7036bd8a903da
